"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-18 10:22:10.122151
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admins')),
    sa.UniqueConstraint('username', name='uq_admin_username')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('final_location_name', sa.String(length=120), nullable=False),
    sa.Column('final_latitude', sa.Float(), nullable=True),
    sa.Column('final_longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('config_locked_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('paused_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)

    op.create_table('locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geofence_radius_m', sa.Float(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('face_card', sa.String(length=10), nullable=True),
    sa.Column('qr_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_locations_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_locations')),
    sa.UniqueConstraint('event_id', 'code', name='uq_location_event_code'),
    sa.UniqueConstraint('event_id', 'face_card', name='uq_location_face_card'),
    sa.UniqueConstraint('qr_token', name='uq_location_qr_token')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_event_id'), ['event_id'], unique=False)

    op.create_table('powers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('max_per_team', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_powers_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_powers')),
    sa.UniqueConstraint('event_id', 'kind', name='uq_power_event_kind')
    )
    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_powers_event_id'), ['event_id'], unique=False)

    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('team_code', sa.String(length=40), nullable=False),
    sa.Column('team_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('leader_name', sa.String(length=120), nullable=True),
    sa.Column('leader_phone', sa.String(length=32), nullable=True),
    sa.Column('leader_email', sa.String(length=160), nullable=True),
    sa.Column('sentence', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('prev_status', sa.String(length=20), nullable=True),
    sa.Column('power_points', sa.Integer(), nullable=False),
    sa.Column('foul_count', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('start_offset_s', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_checkpoint_at', sa.DateTime(), nullable=True),
    sa.Column('frozen_until', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('jack_found_at', sa.DateTime(), nullable=True),
    sa.Column('queen_found_at', sa.DateTime(), nullable=True),
    sa.Column('king_found_at', sa.DateTime(), nullable=True),
    sa.Column('disqualified_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_teams_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('event_id', 'team_code', name='uq_team_event_code'),
    sa.UniqueConstraint('event_id', 'team_name', name='uq_team_event_name')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teams_status'), ['status'], unique=False)

    op.create_table('admin_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=True),
    sa.Column('admin_id', sa.String(length=36), nullable=True),
    sa.Column('admin_username', sa.String(length=80), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('fk_admin_actions_admin_id_admins'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_admin_actions_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_admin_actions_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_admin_actions'))
    )
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_actions_event_id'), ['event_id'], unique=False)

    op.create_table('fouls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('voided', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_fouls_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_fouls_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_fouls_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fouls'))
    )
    with op.batch_alter_table('fouls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fouls_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fouls_team_id'), ['team_id'], unique=False)

    op.create_table('game_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_game_events_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_game_events_team_id_teams'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_events'))
    )
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_events_event_id'), ['event_id'], unique=False)

    op.create_table('help_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=14), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('handled_by', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_help_requests_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_help_requests_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_help_requests'))
    )
    with op.batch_alter_table('help_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_help_requests_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_help_requests_team_id'), ['team_id'], unique=False)

    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('endpoint', sa.String(length=40), nullable=False),
    sa.Column('response', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_idempotency_keys_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('team_id', 'key', name='uq_idempotency_team_key')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_team_id'), ['team_id'], unique=False)

    op.create_table('power_usage',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('target_team_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_power_usage_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_team_id'], ['teams.id'], name=op.f('fk_power_usage_target_team_id_teams'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_power_usage_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_power_usage'))
    )
    with op.batch_alter_table('power_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_power_usage_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_power_usage_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_power_usage_target_team_id'), ['target_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_power_usage_team_id'), ['team_id'], unique=False)

    op.create_table('puzzles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('alt_answers', sa.JSON(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_puzzles_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_puzzles_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_puzzles')),
    sa.UniqueConstraint('location_id', name='uq_puzzle_location')
    )
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzles_event_id'), ['event_id'], unique=False)

    op.create_table('route_stops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_route_stops_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_route_stops_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_stops')),
    sa.UniqueConstraint('team_id', 'location_id', name='uq_route_team_location'),
    sa.UniqueConstraint('team_id', 'seq', name='uq_route_team_seq')
    )
    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_stops_team_id'), ['team_id'], unique=False)

    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('result', sa.String(length=12), nullable=False),
    sa.Column('geofence_flag', sa.Boolean(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_scans_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_scans_location_id_locations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_scans_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scans'))
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_team_id'), ['team_id'], unique=False)

    op.create_table('sentence_fragments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_sentence_fragments_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentence_fragments')),
    sa.UniqueConstraint('team_id', 'seq', name='uq_fragment_team_seq')
    )
    with op.batch_alter_table('sentence_fragments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sentence_fragments_team_id'), ['team_id'], unique=False)

    op.create_table('team_powers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('owned', sa.Integer(), nullable=False),
    sa.Column('used', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_powers_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_powers')),
    sa.UniqueConstraint('team_id', 'kind', name='uq_team_power_kind')
    )
    with op.batch_alter_table('team_powers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_powers_team_id'), ['team_id'], unique=False)

    op.create_table('puzzle_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('puzzle_id', sa.String(length=36), nullable=False),
    sa.Column('answer', sa.String(length=255), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['puzzle_id'], ['puzzles.id'], name=op.f('fk_puzzle_attempts_puzzle_id_puzzles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_puzzle_attempts_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_puzzle_attempts'))
    )
    with op.batch_alter_table('puzzle_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzle_attempts_puzzle_id'), ['puzzle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_puzzle_attempts_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzle_attempts_team_id'))
        batch_op.drop_index(batch_op.f('ix_puzzle_attempts_puzzle_id'))

    op.drop_table('puzzle_attempts')
    with op.batch_alter_table('team_powers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_powers_team_id'))

    op.drop_table('team_powers')
    with op.batch_alter_table('sentence_fragments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sentence_fragments_team_id'))

    op.drop_table('sentence_fragments')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_team_id'))
        batch_op.drop_index(batch_op.f('ix_scans_event_id'))

    op.drop_table('scans')
    with op.batch_alter_table('route_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_stops_team_id'))

    op.drop_table('route_stops')
    with op.batch_alter_table('puzzles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzles_event_id'))

    op.drop_table('puzzles')
    with op.batch_alter_table('power_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_power_usage_team_id'))
        batch_op.drop_index(batch_op.f('ix_power_usage_target_team_id'))
        batch_op.drop_index(batch_op.f('ix_power_usage_status'))
        batch_op.drop_index(batch_op.f('ix_power_usage_event_id'))

    op.drop_table('power_usage')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_team_id'))

    op.drop_table('idempotency_keys')
    with op.batch_alter_table('help_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_help_requests_team_id'))
        batch_op.drop_index(batch_op.f('ix_help_requests_status'))
        batch_op.drop_index(batch_op.f('ix_help_requests_event_id'))

    op.drop_table('help_requests')
    with op.batch_alter_table('game_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_events_event_id'))
        batch_op.drop_index(batch_op.f('ix_game_events_created_at'))

    op.drop_table('game_events')
    with op.batch_alter_table('fouls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fouls_team_id'))
        batch_op.drop_index(batch_op.f('ix_fouls_event_id'))

    op.drop_table('fouls')
    with op.batch_alter_table('admin_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_actions_event_id'))
        batch_op.drop_index(batch_op.f('ix_admin_actions_created_at'))

    op.drop_table('admin_actions')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_status'))
        batch_op.drop_index(batch_op.f('ix_teams_event_id'))

    op.drop_table('teams')
    with op.batch_alter_table('powers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_powers_event_id'))

    op.drop_table('powers')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_locations_event_id'))

    op.drop_table('locations')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_status'))

    op.drop_table('events')
    op.drop_table('admins')
    # ### end Alembic commands ###
