"""location photos

Adds the table for the optional checkpoint photos taken in Setup Routes.
Only a new table - existing data is untouched.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-18 14:42:20.720631
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location_photos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('thumb_content_type', sa.String(length=40), nullable=True),
    sa.Column('thumb', sa.LargeBinary(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_location_photos_location_id_locations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_location_photos')),
    sa.UniqueConstraint('location_id', name='uq_location_photo_location')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('location_photos')
    # ### end Alembic commands ###
