"""puzzle sessions

Built-in checkpoint puzzles: each team's puzzle at each checkpoint (the
version it was dealt and its progress). Only a new table - the old puzzles
tables stay as they were.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-18 15:40:20.356165
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puzzle_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('location_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('state', sa.JSON(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('solved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_puzzle_sessions_location_id_locations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_puzzle_sessions_team_id_teams'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_puzzle_sessions')),
    sa.UniqueConstraint('team_id', 'location_id', name='uq_puzzle_session_team_location')
    )
    with op.batch_alter_table('puzzle_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_puzzle_sessions_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('puzzle_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_puzzle_sessions_team_id'))

    op.drop_table('puzzle_sessions')
    # ### end Alembic commands ###
